//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasMedicasMVC
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel;
  using System.ComponentModel.DataAnnotations;

  public partial class citas
    {
        public int id { get; set; }

    [DisplayName("Medico")]
    public Nullable<int> medico { get; set; }

    [DisplayName("Paciente")]
    public Nullable<int> paciente { get; set; }

    [DataType(DataType.Date)]
    public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
    public string detalles { get; set; }
    [DataType(DataType.MultilineText)]
    public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
